---

- name: Converge
  hosts: all
  gather_facts: true

  roles:
    - role: iamenr0s.ansible_role_swap
      vars:
        # Containers typically cannot enable swap; keep disabled for Molecule
        swap_enabled: false
