---

# Example Playbook for swap management (runtime)

- name: Enable swap (swapon -a)
  hosts: all
  become: true
  roles:
    - role: iamenr0s.ansible_role_swap
      vars:
        swap_enabled: true
        swap_swappiness: 40

- name: Disable swap (swapoff -a)
  hosts: all
  become: true
  roles:
    - role: iamenr0s.ansible_role_swap
      vars:
        swap_enabled: false
